name: MyPlugin
main: testPack.Main
version: 1.0
depend: [TTA, PlayerNPC]
commands:
  killme:
   description: killme
   usage: /killme
  serverChat:
   description: ServerChat
   usage: /ServerChat
  c:
   description: creative
   usage: /c
  SetBiome:
   description: setBiome
   usage: /setBiome
  VilTp:
   description: VilTp
   usage: /VilTp
  k:
   description: k <player> (0 reload) (1 test) (2 macro)
   usage: /k
  velocity:
   description: velocity <player> x y z
   usage: /velocity
  dropQuest:
   description: drop quest
   usage: /dropQuest
  d:
   description: drop quest
   usage: /d
  mob:
   description: mob summon
   usage: /mob
  teleport:
   description: 워프마커 사용 커맨드
   usage: /teleport
  t:
   description: 워프마커 사용 커맨드
   usage: /t
api-version: 1.19